#ifndef COMANDO_H
#define COMANDO_H

enum comando {
  COMANDO_CONECTARSE = 0,
  COMANDO_SALIR,
  COMANDO_ENTRAR,
  COMANDO_DEJAR,
  COMANDO_VER_SALAS,
  COMANDO_VER_USUARIOS,
  COMANDO_VER_USUARIOS_SALAS,
  COMANDO_ENVIAR_MENSAJE,
  COMANDO_CREAR_USUARIO,
  COMANDO_ELIMINAR_USUARIO,
  COMANDO_CREAR_SALA,
  COMANDO_ELIMINAR_SALA,
  COMANDO_HABILITAR_SALA,
  COMANDO_DESHABILITAR_SALA,
  COMANDO_VER_BITACORA
};

#endif
